#server config
server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

# thymeleaf
spring:
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

#dbms
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: practice01
    password: 1234
    
 #jpa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    
#security
  security:
    oauth2:
      client:
        registration: 
          google:
            client-id: 135012990516-cva91j1uo3ugj7m6v10v2ps532dddfeq.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
        
 